version: '2'
services:
    glossary-app:
        image: glossary
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://glossary-postgresql:5432/glossary
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    glossary-postgresql:
        extends:
            file: postgresql.yml
            service: glossary-postgresql
